### ISSUE TITLE
Should the Figure component be a separated from Image

### ISSUE THREAD

**Issue by mjbp** [stormid/scaffold#107]
Figure can contain more than an image - https://html.spec.whatwg.org/multipage/grouping-content.html#the-figure-element.

Putting it in with the same file as the Image component implicitly couples them, and it reduces discoverability.

More controversially - do we need the Figure component? Does it provide any advantage over the figure HTMLElement?

**Comment by Nick-StormID** [comment]
Separating Figure from Image - Agreed. This coupling reduces the flexibility of the component.

Figure at all? I think it was conceived as a convienence option, but within the wider use illustrated by whatwg, I would support it's removal.

**Comment by mjbp** [comment]
Resolved with #118
