### ISSUE TITLE
Utility CSS classes

### ISSUE THREAD

**Issue by mjbp** [stormid/scaffold#135]
A set of CSS conventions for utility classNames that have emerged over time at Storm. To document and standardise them we should create a _utilities.scss partial.

We don't want to bloat the basic CSS bundle so the classes should either be minimal and indicative of naming conventions, or commented out?

Examples:
```
.push-bottom {
    margin-bottom: var(--baseline);
}
.push-bottom--half {
    margin-bottom: calc(var(--baseline)/2);
}
.push-top{
    margin-top: var(--baseline);
}
.push-top--half {
    margin-top: calc(var(--baseline)/2);
}
.soft-bottom {
    padding-bottom: var(--baseline);
}
.soft-top {
    padding-top: var(--baseline);
}
```

**Comment by Nick-StormID** [comment]
Initial set added. Closing.
