### ISSUE TITLE
Update main and initStack implementation

### ISSUE THREAD

**Issue by mjbp** [stormid/scaffold#93]
With the removal of polyfill imports from main.js with #59  and a change in the profile of people writing frontend code at Storm I think it could be time to consider removing main.js and some of the magic involved in JavaScript initialisation.

Designers are writing very little frontend code at Storm these days and one of the primary motivations for the current structure was to hide some confusing polyfilling code and make it easier and more formulaic to initialise components for non-frontend devs. I don't think that is required any more so we can revisit the JS structure.

All of it is up for discussion but to start off we could:

1/ Move all the code from `src/js/modules/main/index.js` into `src/js/index.js` and do away with main.

Hiding the webpack entry point (main) away in the modules folder is counterintuitive for those who need to know how it all works, and has always required additional explanation when onboarding new devs.

Moving everything to index.js and making it the webpack entry point is clearer.

2/ Remove initStack and parallel promisified initialisation to something sequential and less unusual.
I have observed no measurable advantage in promisifying the initialisation functions. Since JavaScript is single threaded there is no real advantage in doing it. It also makes initialisation less predictable since you cannot absolutely guarantee initialisation order.

3/ Use of constants/importer module
The idea of the top-level constants was to allow a way of formalising the async module initialisation process so that it could be abstracted over and boilerplate like `if (document.querySelector('.js-some-element)) import('./modules/some-component').then(module => module('.js-some-element))`, could be removed and `importer('some-module)` used instead.

Putting selectors and per-module config in a separate top-level file as a habit doesn't really add any value if not abstracting, and I am now questioning the value in having the importer in the scaffold at all, and certainly questioning the use of the constants file for non-importer initialisation.

Any other ideas? All suggestions welcome.

**Comment by Nick-StormID** [comment]
I can fully appreciate the rational behind this change. Onboarding to the scaffold has been confussing in places, where native functionality is hidden behind "magic" methods.
As the team grows we should certainly look to keep cross-discipline awareness, but allow specialist roles to follow their best path. I would not wish to constrain a designer's tools to match my skill levels with them.

1 - Agreed.
2 - A simpler implimentation, and a more predictable result is a compelling argument!!
3 - This is much clearer!

**Comment by mjbp** [comment]
Closed with #94
